### PR TITLE
refactor(core-forger): Increase timeout for getting the network state

### PR DESCRIPTION
**Pull request by vasild**
The 2 seconds timeout is too short and can unnecessary blow up the
forging process in cases where it is possible to forge successfully.

Set it to an arbitrary 7 seconds which is block time minus 1 second for
other activities.

Elaborate log messages by explicitly saying "Will not forge" + an
explanation "why" when the code would decide not to forge.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist

- [ ] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by faustbrian** [comment]
This is only a band-aid that hides the issue that the peer verifier is unable to complete all requests in a reasonable amount of time.

Timeouts in the forger should be kept as low as possible to avoid missing a block simply because the request to your relay took too long.

**Comment by vasild** [comment]
> This is only a band-aid that hides the issue that the peer verifier is unable to complete all requests in a reasonable amount of time.

No. The peer verifier is engaged from the `ping()` method and this patch does not touch that timeout - it is still 1.5 seconds.

Notice also that if a peer is at the same height+blockid then the peer verifier will do no extra network calls - that is, timing is the same with and without peer verifier (assuming network calls is where most of the time is spent). See "Case 3" and "Case 5" in https://github.com/ArkEcosystem/core/blob/develop/packages/core-p2p/src/peer-verifier.ts#L69.

> Timeouts in the forger should be kept as low as possible to avoid missing a block simply because the request to your relay took too long.

But if the timeout is too low, and thus the request to `/internal/network/state` times out, then the forger misses a block too.

**Comment by supaiku0** [comment]
Can you rebase this PR onto 2.2?

**Comment by vasild** [comment]
> Can you rebase this PR onto 2.2?

Done.

**Pull request merged**
