### PR TITLE
refactor(core-database-postgres): add nonce column

### PR DESCRIPTION
**Pull request by vasild**
A summary of what changes this PR introduces and why they were made.

## What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Refactor
- [ ] Performance
- [ ] Tests
- [ ] Build
- [ ] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Does this PR release a new version?

- [ ] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `develop` branch, _not_ the `master` branch
- [ ] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by supaiku0** [comment]
The migration also needs to be executed.

**Comment by supaiku0** [comment]
The nonce also needs to be added to the database model here: https://github.com/ArkEcosystem/core/blob/2.6/packages/core-database-postgres/src/models/transaction.ts#L7

**Comment by vasild** [comment]
> The nonce also needs to be added to the database model here: https://github.com/ArkEcosystem/core/blob/2.6/packages/core-database-postgres/src/models/transaction.ts#L7

Done: f5fc1a53c

**Comment by vasild** [comment]
The only remaining failure is:
https://circleci.com/gh/ArkEcosystem/core/55101?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
```
 FAIL  __tests__/functional/transaction-forging/vote.test.ts (87.167s)
  Transaction Forging - Vote
    ✕ should broadcast, accept and forge it [Signed with 1 Passphase] (18076ms)
    ✓ should broadcast, accept and forge it [Signed with 2 Passphrases] (27062ms)
    ✓ should broadcast, accept and forge it [3-of-3 multisig] (36104ms)

  ● Transaction Forging - Vote › should broadcast, accept and forge it [Signed with 1 Passphase]

    expected dc4b8fe0c138d55a4d977904a9d5860f5b8d71782c94b78f15271c27b71b4fb6  to be forged

      27 |         await expect(transactions).toBeAccepted();
      28 |         await support.snoozeForBlock(1);
    > 29 |         await expect(transactions.id).toBeForged();
         |                                       ^
      30 |     });
      31 | 
      32 |     it("should broadcast, accept and forge it [Signed with 2 Passphrases]", async () => {

      at Object.it (__tests__/functional/transaction-forging/vote.test.ts:29:39)
```

That test passes when I run it locally:
```
PASS __tests__/functional/transaction-forging/vote.test.ts (84.364s)
  Transaction Forging - Vote
    ✓ should broadcast, accept and forge it [Signed with 1 Passphase] (18083ms)
    ✓ should broadcast, accept and forge it [Signed with 2 Passphrases] (27055ms)
    ✓ should broadcast, accept and forge it [3-of-3 multisig] (36087ms)
```

I think this test fails sporadically and its failure is not related to the patch in this pull request.

**Pull request merged**
