### PR TITLE
change refs to timelocktype X timelockType

### PR DESCRIPTION
**Pull request by JeremiGendron**
## Proposed changes
simple change of obj prop ref

## Types of changes
What types of changes does your code introduce?
- [ x ] Test (adding missing tests or fixing existing tests)

## Checklist
- [ xx] I have read the [CONTRIBUTING](https://docs.ark.io/docs/contributing) documentation

#761

### CODE REVIEW

**Comment by j-a-m-l** [comment]
I'll go the other way, using `timelockType` instead of `timelocktype`. I'll always prefer using camelCase (or snake_case in other languages) because is better for reading. Apart from that, we're using that style on other properties, so it's a way to avoid mixing them if possible.

What do you think @kristjank ?

**Comment by kristjank** [comment]
Agree with you guys 👍

**Comment by alexbarnsley** [comment]
@JeremiGendron I'd recommend changing all other instances of `timelocktype` to `timelockType`

**Comment by JeremiGendron** [comment]
Doing so

**Comment by JeremiGendron** [comment]
Done closes #761 all instances in the entire repo have been camelCased

**Comment by supaiku0** [comment]
@JeremiGendron You should rebase your changes on top of master and force push again, there's a lot of noise in there from a merge I presume. From what I can tell you effectively touched 3 files and not 28 files. If you need help just ping me.

**Comment by JeremiGendron** [comment]
I normally rebase, made a mistake related to pushing wrongly and had to
debug, now I know where I should rebase if an error like this occurs

**Pull request merged**
