### PR TITLE
chore: CentOS install fixes

### PR DESCRIPTION
**Pull request by adrian69**
## Summary
- Added jemalloc library.
- RedHat derivatives installs update:
  - Added missing flag to `yum clean`.
  - Switched NTP to Chrony (due to CentOS 8 `ntpd` deprecation).
  - Additional record to `pg_hba.conf` (thanks to @rainydio).
## Checklist
- [x] Ready to be merged

### CODE REVIEW

**Comment by alessiodf** [comment]
Is `epel-release` required for CentOS?

I ask because it prevents installation on Fedora as the package is not found. Removing it allows the installation to succeed and then Core works properly on Fedora. If it wasn't needed for CentOS then removing it would make the script work on both CentOS and Fedora.

**Comment by adrian69** [comment]
Although it was originally added because of CentOS6 support, currently `jemalloc` install will fail without it even on CentOS8, so unfortunately it's needed.

**Comment by alessiodf** [comment]
Maybe it could be possible for the script to not abort if `epel-release` is missing then?

**Comment by alessiodf** [comment]
Actually, some other changes would be necessary for Fedora too, probably not worth it if you just want to support CentOS...

**Pull request merged**
