### PR TITLE
chore:  Update port numbers to v2

### PR DESCRIPTION
**Pull request by ciband**
## Proposed changes
Updated legacy port numbers from 4001 to 4003 to match v2 spec.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist

- [X] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [X] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
<!--

## Further comments
N/A

### CODE REVIEW

**Comment by sleepdefic1t** [comment]
This may be causing issues in API V1

### examples

Explorer will not accept a "4003" port, but accepts a 4001 port.

>https://explorer.ark.io:8443/api/peers/get?ip=5.196.105.32&port=4003
```
{"error":"Peer 5.196.105.32:4003 not found","success":false}
```

>https://explorer.ark.io:8443/api/peers/get?ip=5.196.105.32&port=4001
```
{"peer":{"ip":"5.196.105.32","port":4001,"version":"2.0.13","height":6667551,"status":200,"os":"linux","delay":54},"success":true}
```

#

a peer on "4003" will also not accept a "4003" port, but will accept a "4001" port parameter.
>http://5.196.105.33:4003/api/peers/get?ip=5.196.105.32&port=4003
```
{"error":"Peer 5.196.105.32:4003 not found","success":false}
```

>http://5.196.105.33:4003/api/peers/get?ip=5.196.105.32&port=4001
```
{"peer":{"ip":"5.196.105.32","port":4001,"version":"2.0.13","height":6667629,"status":200,"os":"linux","delay":66},"success":true}
```

#

As expected, both of these two "4001" peer calls do not work because we no longer connect on 4001.
>http://5.196.105.32:4001/api/peers/get?ip=5.196.105.32&port=4003
```
{"error":"should have required property 'port'","success":false}
```

> http://5.196.105.32:4001/api/peers/get?ip=5.196.105.32&port=4001
```
{"error":"should have required property 'port'","success":false}
```

This leads me to suspect that this PR may also resolve the issue outlined above.

**Comment by alexbarnsley** [comment]
I'm not an expert so I'm not going to review this PR, however I believe those peer lists are designed for P2P interaction, not for the API. Also, for the purposes of consistency, you didn't update the port numbers for devnet or the test peers.

**Comment by sleepdefic1t** [comment]
"4001" is supposed to be the P2P API,
but isn't `/api/peers/get` supposed to be a Public API endpoint?

If this file is to remain using port 4001 for P2P, 
then should `peers/get` not be public API, or is this endpoint using the incorrect data?

**Comment by ciband** [comment]
ok.  That makes more sense I think.

This is the first I've seen of the :4001/config pattern.  Doing this in cpp-client might solve some of our v1 issues after the v2 upgrade.

I will close this PR then.

Thanks for the help, @alexbarnsley

**Comment by kristjank** [comment]
the configuration call in v2: https://docs.ark.io/api/public/v2/node.html#retrieve-the-configuration @ciband @sleepdefic1t

**Comment by ciband** [comment]
Thank you @kristjank

**Pull request closed without merging**
