### PR TITLE
test(core-transactions): increase coverage to 100%

### PR DESCRIPTION
**Pull request by sebastijankuzner**
## Summary

What changes are being made?

Rewrite tests for core-transactions. Refactor some things that causes a problem with tests.

## Checklist

- [ ] Documentation _(if necessary)_
- [x] Tests _(if necessary)_
- [x] Ready to be merged

Some things that need a better look and maybe refactoring were marked with todo comment (handler.test.ts).

### CODE REVIEW

**Comment by faustbrian** [comment]
You can check https://codecov.io/gh/ArkEcosystem/core/tree/test%2Ftest-core-transactions/packages/core-transactions/src to see what is still missing coverage to get to 100%.

**Comment by sebastijankuzner** [comment]
Coverage is increased to almost 100%, some code cannot be tested, because it is unreachable. There are some refactoring in the core-transaction package and included merge from branch: fix(core-transactions): undefined pool variable #3535.

**Comment by faustbrian** [comment]
> Coverage is increased to almost 100%, some code cannot be tested, because it is unreachable.

There is no such thing as code that can't be tested but if it is difficult to test certain code that means you should refactor it to get coverage for it or remove it if you are certain that it is unreachable by the application.

**Comment by sebastijankuzner** [comment]
The coverage should now be 100%.

**Pull request merged**
