### PR TITLE
WIP: perf(core-transaction-pool-mem): Do not call getTransactionIdsForForging(0, pool size)

### PR DESCRIPTION
**Pull request by vasild**
Requesting lots of transactions from getTransactionIdsForForging()
can be slow and we only need a few (usually 150) => avoid calling
getTransactionIdsForForging(0, pool size) unnecessary.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist

- [ ] I have read the [CONTRIBUTING](https://docs.ark.io/developers/guidelines/contributing.html) documentation
- [ ] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by vasild** [comment]
This patch assumes that most of the transactions in the pool will pass `checkDynamicFeeMatch()` and `checkApplyToBlockchain()`. But if this is not the case, then the performance will be worse than it is before the patch. For example if we have a pool with 30'000 transactions that do not pass those tests, we will end up calling:
```
getTransactionIdsForForging(0, 200)
getTransactionIdsForForging(0, 400)
getTransactionIdsForForging(0, 800)
getTransactionIdsForForging(0, 1600)
getTransactionIdsForForging(0, 3200)
getTransactionIdsForForging(0, 6400)
getTransactionIdsForForging(0, 12800)
getTransactionIdsForForging(0, 25600)
getTransactionIdsForForging(0, 30000)
```
which is worse than before the patch, just:
```
getTransactionIdsForForging(0, 30000)
```

Thus, performance-wise, this patch depends on not allowing too low fee transactions to enter the pool in the first place.

**Comment by vasild** [comment]
Maybe one of these could be better:
* Try (0, N) and if it does not deliver then directly (0, pool size), instead of (0, N*2), (0, N*4), ... (0, pool size)
* Try (0, N) and if it does not deliver then try (N, M) and handle possible inconsistencies due to pool being changed between the calls

**Comment by kristjank** [comment]
@vasild as you said, this is an issue. We are changing this and moving dynamic fee check on the pool entry door, meaning this function can be simplified back to return only first 150 transactions from the pool.

**Comment by kristjank** [comment]
@vasild join this branch here please #1343

**Comment by vasild** [comment]
Overridden by https://github.com/ArkEcosystem/core/pull/1343

**Pull request closed without merging**
