### PR TITLE
chore: remove sequelize

### PR DESCRIPTION
**Pull request by faustbrian**
## Proposed changes

Removes **core-database-sequelize** which can now be found here https://github.com/ArkEcosystem/core-plugins so we can focus on postgresql to optimise database performance and get rid of things like mysql and sqlite.

## Types of changes

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/developers/guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by fix** [comment]
i disagree with this, please resubmit a PR to add it back

**Comment by faustbrian** [comment]
https://git-scm.com/docs/git-revert

**Comment by fix** [comment]
Yes i am sure you know how to do it.
Either that or either have a `core-database-sqlite` plugin before deprecating. This is highly important, we had already this discussion but we do need no install for database option out of the box

**Comment by fix** [comment]
ok alternatively, is it possible to have:
- a config able to use the new core-database-sequelize
- ditch the 'non supported' part on this new repository
@faustbrian

**Pull request merged**
