### PR TITLE
[WIP] feat(transaction-pool): check all peer fees to determine if broadcast the transaction

### PR DESCRIPTION
**Pull request by zillionn**
## Proposed changes
This is my proposal. Ditch `minFeeBroadcast` in favor of this:
- When peer discovery, get peer fees from `PEER_IP/api/node/configuration`
- When receive a transaction, check if any peer will accept it
- If at least 1 peer will accept it, add it to broadcast queue, otherwise don't broadcast it

This is how it looks:

2 transfer txs with fee `0.00000123`
> [2018-12-08 22:26:05][DEBUG]   : Transaction b9e743501a9d593bf09cf5f1d331df8c06c6a331cedd3058cf4d439a97bf88f7 not eligible for broadcast - no peers match fee of 0.00000123 DѦ
[2018-12-08 22:26:05][DEBUG]   : Transaction b9e743501a9d593bf09cf5f1d331df8c06c6a331cedd3058cf4d439a97bf88f7 not eligible to enter pool - fee of 0.00000123 DѦ is smaller than minimum fee 0.00258 DѦ
[2018-12-08 22:26:05][DEBUG]   : Transaction 746c7a0a2875d58a2391eab72b262e926c055dcbca83a61557774bec3978bdf4 not eligible for broadcast - no peers match fee of 0.00000123 DѦ
[2018-12-08 22:26:05][DEBUG]   : Transaction 746c7a0a2875d58a2391eab72b262e926c055dcbca83a61557774bec3978bdf4 not eligible to enter pool - fee of 0.00000123 DѦ is smaller than minimum fee 0.00257 DѦ

2 transfer txs with fee `0.01`

> [2018-12-08 22:24:29][DEBUG]   : Transaction 8edde673db13d9dafbcd076c0c3787af75b7a7526e927c2fa67faa7a1464151c eligible for broadcast - 72 peers accept fee of 0.01 DѦ
[2018-12-08 22:24:29][DEBUG]   : Transaction 8edde673db13d9dafbcd076c0c3787af75b7a7526e927c2fa67faa7a1464151c eligible to enter pool - fee of 0.01 DѦ is greater than minimum fee (0.00257 DѦ)
[2018-12-08 22:24:29][DEBUG]   : Transaction 36554fd46cd22bcd2fa6446e4ba175af76c3f5d203e333f1ecf161484745ab3c eligible for broadcast - 72 peers accept fee of 0.01 DѦ
[2018-12-08 22:24:29][DEBUG]   : Transaction 36554fd46cd22bcd2fa6446e4ba175af76c3f5d203e333f1ecf161484745ab3c eligible to enter pool - fee of 0.01 DѦ is greater than minimum fee (0.00257 DѦ)
[2018-12-08 22:24:29][INFO]    : Received 2 transactions (accept: 2 broadcast: 2 excess: 0 invalid: 0).
[2018-12-08 22:24:29][DEBUG]   : Broadcasting 2 transactions to 20 peers

2 transfer txs with fee `0.000003`

> [2018-12-08 22:25:13][DEBUG]   : Transaction 7314c6423657193d99d9050bb94f635698bbf5eaf351a97fd6533aaa051882f8 eligible for broadcast - 3 peers accept fee of 0.000003 DѦ
[2018-12-08 22:25:13][DEBUG]   : Transaction 7314c6423657193d99d9050bb94f635698bbf5eaf351a97fd6533aaa051882f8 not eligible to enter pool - fee of 0.000003 DѦ is smaller than minimum fee 0.00258 DѦ
[2018-12-08 22:25:13][DEBUG]   : Transaction ee322b7c3a8334393452f4714618853e33eb045a15b5aad67765d5f7dea2e891 eligible for broadcast - 3 peers accept fee of 0.000003 DѦ
[2018-12-08 22:25:13][DEBUG]   : Transaction ee322b7c3a8334393452f4714618853e33eb045a15b5aad67765d5f7dea2e891 not eligible to enter pool - fee of 0.000003 DѦ is smaller than minimum fee 0.00257 DѦ
[2018-12-08 22:25:13][INFO]    : Received 2 transactions (accept: 0 broadcast: 2 excess: 0 invalid: 2).
[2018-12-08 22:25:13][DEBUG]   : Broadcasting 2 transactions to 20 peers

Please test if you're interested.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist

- [ ] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by vasild** [comment]
* `minFeeBroadcast`'s idea is that a relay has to spend some resources in order to broadcast a transaction and those resources cost money. So, to avoid abuse, `minFeeBroadcast` can be set according to the relay's configuration and specification. This is not related to other relays' setups.

* This change would force a relay to broadcast if his peers have lower acceptance fees.

* It could happen that none of his peers would accept the transaction in their pool, but some of their peers would accept it. The patch in this proposal would fail to propagate the transaction to those nodes that would have accepted it.

**Comment by zillionn** [comment]
1. The problem with `minFeeBroadcast` is that it's a temporary solution and it has nothing to do with the network wide fees. If forgers lower their fees, there is no way for the relays to find out about the change. The only way is an update or old relays will never broadcast. Current implementation with `minFeeBroadcast: 3000` will never broadcast a tx with fee `300`, and this one will, because `3 peers/forgers` accept fee `300`.
2. That's the whole point.
3. This could happen even now. Transactions are broadcasted to 20 `random` peers, not to all peers. If a relay can't connect to other peers, there're many other issues that will occur.

I strongly recommend testing it to see how it works.

IMO the best solution is to get only the forgers fees, not all peers', but I have no idea which peer is a forger...

Hm, just came up with an idea. How about to use the `feeStatistics` not the relay's fee policy? The `feeStatistics.minFee` for the type should be the lowest fee that a forger forged that type of tx. Am I wrong?
https://dexplorer.ark.io/api/v2/node/configuration

@kristjank Whats' your opinion?

**Comment by vasild** [comment]
Bitcoin core has `-minrelaytxfee`:
``` 
 -minrelaytxfee=<amt>
       Fees (in BTC/kB) smaller than this are considered zero fee for relaying,
       mining and transaction creation (default: 0.00001)
```

See also https://bitcoin.org/en/glossary/minimum-relay-fee

**Comment by zillionn** [comment]
@vasild Bitcoin also uses PoW 😄

**Comment by zillionn** [comment]
Yeah, using `feeStatistics.minFee` will not work. When forgers lower their fees and there is no forged block with the new lower fees, `feeStatistics.minFee` will still return the old high fees and the relays will not broadcast the new txs...

**Comment by zillionn** [comment]
OK, I believe this is the correct long term solution:
- Add a new column `min_accept_fee` in the `transactions` table
- When I forger forges a tx, insert also it's `min_accept_fee` for the tx
- Now we'll know the lowest the forger will accept as `feeStatistics.minAcceptFee` and we'll use it not only when broadcasting, but also when accepting txs in the pool!

What do you think?

**Comment by zillionn** [comment]
Moving here: https://github.com/ArkEcosystem/core/issues/1685

**Pull request closed without merging**
