### PR TITLE
fix: getBlocks log wording

### PR DESCRIPTION
**Pull request by alexbarnsley**
## Proposed changes

Improve readability of log message

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by ItsANameToo** [comment]
You haven't read the contributing document? 🤔

**Comment by alexbarnsley** [comment]
:colbert:

**Comment by ItsANameToo** [comment]
That has no power here

**Comment by boldninja** [comment]
colbert

**Comment by alexbarnsley** [comment]
see, Rok gets it :trollface:

**Comment by ItsANameToo** [comment]
Rok has too much free time since v2 release 😂

**Pull request merged**
