### PR TITLE
[WIP] Feat/ipfs support

### PR DESCRIPTION
**Pull request by JeremiGendron**
## Proposed changes

very basic implementation of core-ipfs, has node running capability and a few tests to demonstrate plausibility.

Please provide feedback, I'm very interested in working on this.

For example, which codec to use by default?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/developers/guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by faustbrian** [comment]
There are now specific plans yet how IPFS is going to be implemented into core so if you have a use-case for this right now you should publish this as your own plugin like other community developers have done.

**Comment by JeremiGendron** [comment]
My mistake

**Comment by kristjank** [comment]
@JeremiGendron thanks for being proactive. This is not a mistake, we have some ideas, but as Brian said nothing is outlined, so if you want I can try to help you with requirements and get this thing moving forward, maybe we do some tests and stuff, in terms of:
- what does this mean from HW point of view
- expanding transaction and store data along the lines
- what can a sender/client store
- the retrieving process, how would it look like from clients perspective...
- how secure

Maybe do a fork of core, and we continue there with tests and stuff 👍

**Comment by JeremiGendron** [comment]
I have to do more research before outlining suggestions

**Pull request closed without merging**
