### PR TITLE
Updated for v2

### PR DESCRIPTION
**Pull request by kalgoop**
'delay' is changed to 'latency' in v2

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/developers/guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by alexbarnsley** [comment]
Thanks for your change. This should be split up into 2 methods though, as currently the client is designed to work with both v1 and v2 networks, so it should check which version to see which column needs to be sorted by.

**Comment by kalgoop** [comment]
> 
> 
> Thanks for your change. This should be split up into 2 methods though, as currently the client is designed to work with both v1 and v2 networks, so it should check which version to see which column needs to be sorted by.

Thanks for the advice. Updated.
It checks if peers object has a property of 'delay' or 'latency', and accordingly uses orderBy operation.

**Comment by fix** [comment]
this might be breaking with v1 protocol p2p layer.

**Comment by kalgoop** [comment]
@fix can you elaborate how it may break with v1 p2p?
I feel this will only improve situation from previous version.

**Pull request merged**
