### PR TITLE
fix: reply, on node configuration API endpoint, with integer ports

### PR DESCRIPTION
**Pull request by j-a-m-l**
## Proposed changes
Devnet and Mainnet were returning a different type on the node configuration endpoint (http://167.114.29.54:4003/api/v2/node/configuration). It may be caused by loading the ports from the environment, configuration files, or other causes.

This PR enforces that, independently of the cause, the API ports of the response, are always integers.

## Types of changes
- [x] Bugfix (non-breaking change which fixes an issue)
- [x] Test (adding missing tests or fixing existing tests)

## Checklist
- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by faustbrian** [comment]
Should be done in the transformer rather then method. Will be fixed anyways in https://github.com/ArkEcosystem/core/pull/1625,

**Comment by j-a-m-l** [comment]
Reopen to fix the problem while the TypeScript migration is being done.

**Comment by faustbrian** [comment]
The typescript migration will be done mid next week and there won't be a new release before that for such a small change.

**Comment by j-a-m-l** [comment]
So, should we stop working on the current PRs or create new ones?

**Comment by faustbrian** [comment]
Would be advised unless it is a critical bug fix or security issue, that is why all other PRs are open and not getting merged.

**Comment by j-a-m-l** [comment]
Wouldn't it be better to include this small fix anyway? If one of those PR is merged because it's a critical fix, we would fix both problems.

**Comment by faustbrian** [comment]
It won't be merged until TS is done next week so just leave it closed.

**Pull request closed without merging**
