### PR TITLE
fix(core-transaction-pool): wallet-manager fallback to database wallet manager findByIndex() when no "local" match

### LINKED ISSUE #3242: [2.6][T3] htlc refunds of bootstrapped locks cannot be applied to sender but increases nonce
HTLC refunds currently throw an error in the `applyToSender` method (probably since #3183).

The assertions in the method fail since the wrong wallet manager is used to retrieve the lockWallet and lock.

### PR DESCRIPTION
**Pull request by air1one**
## Summary

Resolves #3242 

Transaction pool wallet manager : try database wallet manager findByIndex() when local findByIndex() doesn't return a match.

We might not have all existing wallets indexes on transaction pool wallet manager : so in case we get no match we should try with database wallet manager.

## Checklist

- [ ] Documentation _(if necessary)_
- [x] Tests _(if necessary)_
- [x] Ready to be merged

### CODE REVIEW

**Comment by dated** [comment]
With these changes the following lines become obsolete, is that right?

https://github.com/ArkEcosystem/core/blob/8f028f8cafa096e7c3cd8d811f46f91719deae96/packages/core-transactions/src/handlers/htlc-refund.ts#L53-L56

Instead, we can call `findByIndex` on the wallet manager passed to the `throwIfCannotBeApplied` method directly.

**Comment by dated** [comment]
And another question for my personal understanding: should the Wallet Managers be allowed to be out of sync at all?

**Comment by supaiku0** [comment]
@dated Initially the PoolWalletManager has no wallets and clones every database wallet that is missing. The reason why it is an issue for HTLC is because `findByIndex` is called directly, which doesn't have the fallback to the database wallets as `findByAddress/findByPublicKey` do. This PR adds the fallback.

> With these changes the following lines become obsolete, is that right?

Yes, these should be obsolete now. @air1one

**Comment by dated** [comment]
Understood! Thanks for the explanation!

**Comment by air1one** [comment]
> With these changes the following lines become obsolete, is that right?

No I think it's better to keep it this way, we actually want to check just against the database wallets, with associated lock transaction forged. (we don't want to validate if the lock transaction is still in the pool and was applied just to tx pool wallet, even though in theory this shouldn't happen)

**Pull request merged**
