### PR TITLE
Export & use core-container types

### PR DESCRIPTION
**Pull request by paroxysm**
## Proposed changes
Address #1789 and also further propagate `core-logger`'s `AbstractLogger` type usage.
We're leveraging ts generics to be able to retrieve typed objects directly from the `Container` class.
For the time-being, the generic is defaulted to `any` to prevent compilation issues, but in the future, as we expose more module typedefs, we can remove that default to enforce that we always get typed values from the `Container`

We're also introducing `core-logger` as a dependency to every module that was previously grabbing a reference via `container.resolvePlugin('logger')`

I'm trying to be careful not to introduce a circular dependency. I know there can definitely be one in `core-container` and `core-logger` when they both try to import each other's types. For this edge-case we can break the pattern by having `core-logger` not import `core-container`'s typedefs but it's not that big of an issue.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by paroxysm** [comment]
Looking into them..

**Comment by paroxysm** [comment]
@faustbrian  These failures don't appear to have anything to do w/ my changes. There is brittleness in there somewhere that's surfacing now. The code that was merged doesn't even affect the module whose tests are failing

**Comment by paroxysm** [comment]
@faustbrian I can reproduce these failures on the develop branch w/o the changes in this PR. Seems something else recent is causing these failures.

**Comment by paroxysm** [comment]
It's strange tho, there should've been a 100% failure across all CI runs but only a few failed while some passed....

**Comment by faustbrian** [comment]
@paroxysm you can use https://help.github.com/articles/closing-issues-using-keywords/ if you want to automatically close issues as resolved.

Instead of `Address #1789` write `Resolves #1789`.

**Comment by paroxysm** [comment]
Thanks, that's really nifty @faustbrian!

**Pull request merged**
