### PR TITLE
chore: adhere to naming and readme conventions

### PR DESCRIPTION
**Pull request by dated**
## Proposed changes

 - Changes `ARK` to `Ark` where appropriate
 - Changes readme structure and replaces any reference to imgur with local images

## Types of changes

- [x] Docs (documentation only changes)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation

### CODE REVIEW

**Comment by dated** [comment]
> Copying the banner.png into every directory is unnecessary duplication as the banner will never change. You should simply put the banner into the root of the repository and link to that.

Changed that back for all packages except `client` and `crypto` which have custom banners.

**Comment by alexbarnsley** [comment]
It's worth noting that the banners may need to be within packages for when they are published to npm. Although that being said, it looks like it doesn't work for the same directory either:

https://www.npmjs.com/package/@arkecosystem/crypto

Could it be worth doing the full URL to the image?

**Comment by dated** [comment]
My personal preference would be to add `?sanitize=true` if that works, but I'll wait for your input.

**Comment by faustbrian** [comment]
Do the `?sanitize=true`, looks the cleanest.

**Comment by alexbarnsley** [comment]
I agree, `?sanitize=true` looks like a good way of doing it 👌

**Comment by dated** [comment]
I've looked at this again and I think the sanitize method does not work after all. The only fix seems to be to use absolute URLs. This issue affects all relative paths, so also the `All Contributors` and `MIT` links are broken on the npm website.

**Comment by dated** [comment]
Yep, doesn't work. I'll change the links and images to absolute paths later today.

**Pull request merged**
