### PR TITLE
chore: use kebab case for aliases

### LINKED ISSUE #2282: Inconsistent nomenclature of aliases
**Describe the problem**

Some packages have a hyphenated alias, other use camelcase. Is there a reason for this?

```
alias: "databaseManager",
alias: "error-tracker",
alias: "error-tracker",
alias: "event-emitter",
alias: "json-rpc",
alias: "logManager",
alias: "transactionPool",
alias: "vote-report"
```

### PR DESCRIPTION
**Pull request by dated**
## Proposed changes

Changes the following aliases:

```
databaseManager -> database-manager
logManager      -> log-manager
transactionPool -> transaction-pool
```

Closes #2282.
## Types of changes

- [x] Other... Please describe: chore

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by gsilvestri** [comment]
Camel Case is the most used standard for object oriented programmig, JavaScript takes some common features of object oriented programming this is more visible with the introduction of TypeScript in the ARK core (Objects, classes, public/private properties, etc...)

Are You sure is a good idea to NOT use camel case with Typescript as it is the common choice for OO programming languages??

**Comment by faustbrian** [comment]
@dated conflicts

**Comment by dated** [comment]
@faustbrian resolved

**Comment by faustbrian** [comment]
@dated will test it tomorrow and then merge.

**Comment by dated** [comment]
I'll have a look ASAP.

**Comment by dated** [comment]
The sqlite build fails from time to time. I restarted the job.

**Pull request merged**
