### PR TITLE
chore(crypto): add txs with 2nd signature failes to exceptions on devnet 

### PR DESCRIPTION
**Pull request by roks0n**
## Proposed changes
Adds invalid transactions to exceptions on devnet which prevent nodes to get sync up: https://github.com/ArkEcosystem/core/issues/1672

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

I've managed to get my forging devnet node to sync up and get up to hight by adding these txid's to exceptions.

### CODE REVIEW

**Comment by zillionn** [comment]
Rolled back to `900,000` and I was unable to sync. Error at `913,053`.

After loading the snapshot from `https://dsnapshots.ark.io/devnet-v2`, I'm in sync.

**Comment by roks0n** [comment]
I've now rolled back to 900,000 as well and can check and add more transactions to exceptions.

**Comment by zillionn** [comment]
They are too many, you should not waste your time. Just load the snapshot.

**Comment by roks0n** [comment]
I see, I hope there would only be a few. Ok, feel free to close the PR

**Pull request closed without merging**
