### PR TITLE
feat: pure PostgreSQL integration

### PR DESCRIPTION
**Pull request by faustbrian**
## Proposed changes

This PR integrates https://github.com/vitaly-t/pg-promise which provides superior performance and resolves https://github.com/ArkEcosystem/core/issues/967.

This paves the way for future optimisations on the database layer without having to do any comprises because we have to keep in mind how mysql, sqlite or god knows what work as our main focus should be one engine and that is postgres.

The performance impact on the API has already been quite nice after some initial testing as count queries are now possible even on low-end servers which allows us to provide end-users with better pagination of data and serve that data faster.

**This is a work in progress as some adjustments are still left to be done but syncing with devnet just finished so that already works.**

**Todo**
- [x] Create migrations
- [x] Create sql query files
- [x] Create models
- [x] Create repositories
- [x] Create helpers to interact with sql files
- [x] Adjust query builder to pg-promise placeholder syntax
- [x] Adjust query builder to make use of pg-promise helpers for formatting
- [x] Decouple core-api from any database specifics
- [ ] ~~Decouple core-graphql from any database specifics~~ **core-graphql currently has no test suite so that will be done once @air1one implemented a test suite**

## Types of changes

- [x] New feature (non-breaking change which adds functionality)
- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/developers/guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by faustbrian** [comment]
@alexbarnsley @supaiku0 This is soon ready for testing. I just have to resolve an issue where `estimate` queries fail if they contain any `WHERE` clauses here https://github.com/ArkEcosystem/core/blob/feat/pg-promise/packages/core-api/lib/repositories/repository.js#L22.

**Comment by faustbrian** [comment]
@supaiku0 @alexbarnsley ready for testing

**Comment by vitaly-t** [comment]
Perhaps the best-done example of integrating `pg-promise` into a serious product: [Lisk](https://github.com/LiskHQ/lisk).

**Comment by fix** [comment]
@vitaly-t are you trolling here?

**Comment by vitaly-t** [comment]
@fix What's that supposed to mean? 😕 

This PR refactors the code to use `pg-promise`. I gave the link to a project that illustrates the best integration approach for it, as a perfect example.

**Comment by fix** [comment]
I know very well lisk and how it was integrated at that time.

I was meaning, do you imply ARK is not serious?

**Comment by vitaly-t** [comment]
> I was meaning, do you imply ARK is not serious?

I didn't even look at this project, that's beside the point. I only look at popular projects that try to integrate with `pg-promise` and give valuable advises.

You are looking at it the wrong way.

**Comment by vitaly-t** [comment]
Oh, good to know. I'm still assisting them with the database layer when I have time. May I ask why you left?

**Comment by fix** [comment]
We had complete divergent view on what blockchain should be, and how this should be implemented

**Comment by supaiku0** [comment]
There's at least one place where we occasionally pass an empty array to a query with an `WHERE ... IN` clause, producing faulty sql: `SELECT * FROM table WHERE id IN ()` resulting in an exception.

This happens in`core-transaction-pool-redis` at `removeForgedAndGetPending`. It was fine before, because joining an empty array returns an empty string and `SELECT * FROM table WHERE id IN ('')` is valid.

I think we should add additional checks to each repository right before we pass an array to any query with an `WHERE ... IN` clause and return early with an empty result just to be safe. We don't have many of them anyway.

Regarding votebalance:
Since `votebalance` is lowercase and not camelCase, the function `camelize-columns` doesn't apply here. I opened a PR #981 to rename it, so we don't have to add any workarounds.

**Comment by vitaly-t** [comment]
@supaiku0 See [WHERE col IN Query with empty array as parameter](https://stackoverflow.com/questions/49188085/where-col-in-query-with-empty-array-as-parameter).

**Pull request merged**
