### PR TITLE
feat(core-api): include core version in node/configuration

### PR DESCRIPTION
**Pull request by dated**
Adds the core version to the response body of the `node/configuration` endpoint. The Desktop Wallet currently needs that information when adding a custom peer.

## What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Refactor
- [ ] Performance
- [ ] Tests
- [ ] Build
- [ ] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch
- [x] All tests are passing
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by supaiku0** [comment]
Thanks! I like the idea, but can you turn it into an object like this: `core:  { version }`? This way we can easily extend it with other core specific data later on.

**Comment by dated** [comment]
Sure :thumbsup:

**Comment by faustbrian** [comment]
@dated conflicts

**Comment by dated** [comment]
@faustbrian resolved

**Comment by dated** [comment]
```
  ● Transaction Forging - HTLC Claim › should broadcast, accept and forge it [Signed with 1 Passphase]

    expected d40e81b22981c8a9744ffdef8d477357f6d70f6213aba4b73bd44117ccac515f  to be forged

      40 |         await expect(lockTransaction).toBeAccepted();
      41 |         await support.snoozeForBlock(1);
    > 42 |         await expect(lockTransaction.id).toBeForged();
         |                                          ^
      43 | 
      44 |         // Submit htlc claim transaction
      45 |         const transaction = TransactionFactory.htlcClaim({

      at Object.it (__tests__/functional/transaction-forging/htlc-claim.test.ts:42:42)
```

**Pull request merged**
