### PR TITLE
Fix handling of "boolean" environment variables

### PR DESCRIPTION
**Pull request by vasild**
`expression || true` always evaluates to `true`.
`expression || false` always evaluates to `expression`.

So, while it makes perfect sense to have something like
`process.env.ARK_JSON_RPC_PORT || 8080`, constructs like
`process.env.ARK_TRANSACTION_POOL_ENABLED || true` mean that it is not
possible to disable (the transaction pool).

`process.env.ARK_DB_LOGGING || false` is just clutter and is the same as
`process.env.ARK_DB_LOGGING`.

After this change it is possible to disable
ARK_API_ENABLED
ARK_GRAPHQL_ENABLED
ARK_TRANSACTION_POOL_ENABLED
ARK_WEBHOOKS_ENABLED
by not setting the relevant variable in the environment (or setting it
to an empty string).

This is a behavioral change - users that did not had e.g.
ARK_TRANSACTION_POOL_ENABLED set in the environment before this change
would have it enabled, whereas after this change it will be disabled for
them and in order to enable it they must define
ARK_TRANSACTION_POOL_ENABLED in the environment (to some value).

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist

- [ ] I have read the [CONTRIBUTING](https://docs.ark.io/docs/contributing) documentation
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by vasild** [comment]
If this looks too risky, maybe add another change on top of it that renames FOO_ENABLED to FOO_DISABLED, so that things that were (permanently) enabled before keep being enabled (assuming the user does not have FOO_ENABLED or FOO_DISABLED in the environment)? And then in order to disable, the user would have to explicitly define FOO_DISABLED to some non-empty value.

**Comment by vasild** [comment]
Aha! Travis choked on this:
```
[2018-08-01 19:29:17][WARN]    : Redis transaction pool disabled - please enable if run in production
[2018-08-01 19:29:18][ERROR]   : Could not get transactions for forging from Redis:  TypeError: Cannot read property 'join' of undefined
```

**Comment by faustbrian** [comment]
```
This is a behavioral change - users that did not had e.g.
ARK_TRANSACTION_POOL_ENABLED set in the environment before this change
would have it enabled, whereas after this change it will be disabled for
them and in order to enable it they must define
ARK_TRANSACTION_POOL_ENABLED in the environment (to some value).
```

Things like a transaction pool should always be enabled by default. We could modify the commander but not everyone uses the commander, especially not for a local environment.

The defaults that were in place before this change should be retained.

**Comment by vasild** [comment]
@faustbrian so, go with https://github.com/ArkEcosystem/core/pull/792#issuecomment-409694044?

**Comment by faustbrian** [comment]
Seems like an OK solution for now.

**Comment by faustbrian** [comment]
Travis is still failing at the moment because the transaction pool is not enabled by default.

**Comment by vasild** [comment]
I just extended this change to also rename ..._ENABLED to ..._DISABLED so that things remain enabled by default (assuming people do not have ..._DISABLED defined in their environment).

**Pull request merged**
