### PR TITLE
fix(core-json-rpc): retrieve bip38 wallet after creating it and return the encoded WIF

### PR DESCRIPTION
**Pull request by zillionn**
## Proposed changes
When there is no `encryptedWif` in the database:
https://github.com/ArkEcosystem/core/blob/6518001679ed9a08924e36c33474c5305fd78dae/packages/core-json-rpc/lib/server/utils/bip38-keys.js#L8-L10

the `catch` is returning `encryptedWif` not encoded:
https://github.com/ArkEcosystem/core/blob/6518001679ed9a08924e36c33474c5305fd78dae/packages/core-json-rpc/lib/server/methods/wallets/bip38/create.js#L20-L36

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist

- [ ] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by zillionn** [comment]
Please test! Sometimes I get this error:
> {
    "error": {
        "code": -32603,
        "data": "TypeError: privateKey.copy is not a function\n    at encodeRaw (/home/darknodeuser/ark-core/node_modules/wif/index.js:33:14)\n    at Object.encode (/home/darknodeuser/ark-core/node_modules/wif/index.js:47:60)\n    at method (/home/darknodeuser/ark-core/packages/core-json-rpc/lib/server/methods/wallets/bip38/create.js:33:27)",
        "message": "privateKey.copy is not a function"
    },
    "id": "unique-request-id",
    "jsonrpc": "2.0"
}

**Comment by zillionn** [comment]
I'm giving up.

**Comment by alexbarnsley** [comment]
No quitting :danstop:

**Comment by zillionn** [comment]
It's the stupid tests, I hate them! They just don't pass because this
https://github.com/ArkEcosystem/core/blob/6518001679ed9a08924e36c33474c5305fd78dae/packages/core-json-rpc/__tests__/wallets.test.js#L157-L160

returns this
> data:
       { jsonrpc: '2.0',
         id: '8612fcb3-e03a-4c38-8657-d41b9d8b6552',
         error:
          { code: -32603,
            message: 'privateKey.copy is not a function',
            data:
             'TypeError: privateKey.copy is not a function\n    at encodeRaw (/Work/ark-core/node_modules/wif/index.js:33:14)\n    at Object.encode (/Work/ark-core/node_modules/wif/index.js:47:60)\n    at encode (/Work/ark-core/packages/core-json-rpc/lib/server/methods/wallets/bip38/create.js:34:29)' } } }

**Comment by faustbrian** [comment]
@zillionn adjusted it for you

**Comment by zillionn** [comment]
OK thanks, but will the tests pass???

**Comment by faustbrian** [comment]
Closing this as it required more changes after looking at the full picture.

https://github.com/ArkEcosystem/core/pull/1653

**Pull request closed without merging**
