### PR TITLE
docs: fix broken references to plugin docs

### LINKED ISSUE #2262: Docs re-org broke some readme.md links in core
Docs issue [#311](https://github.com/ArkEcosystem/docs/issues/311) re-organised the plugins into required,optional and deprecated categories, but links in the core repo readme.md for each plugin now are invalid.

### PR DESCRIPTION
**Pull request by jamesbooker**
## Proposed changes

Updates various readme.md files to resolve #2262 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [X] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist

- [X] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by jamesbooker** [comment]
> Please rebase this to develop.

I am struggling to do this, as it appears it's reverting dependencies to older versions? do I 'accept incoming changes'?

**Comment by jamesbooker** [comment]
> > Please rebase this to develop.
> 
> I am struggling to do this, as it appears it's reverting dependencies to older versions? do I 'accept incoming changes'?

OK I have rebased, accepted changes from the develop branch and re-commited

**Comment by faustbrian** [comment]
It looks like you merged instead of doing a rebase, might be easier to close the PR and resubmit it based on develop.

**Comment by jamesbooker** [comment]
> It looks like you merged instead of doing a rebase, might be easier to close the PR and resubmit it based on develop.

OK

**Pull request closed without merging**
